### PR TITLE
Configure urls

### PR DESCRIPTION
**Pull request by pascalj**
Previously we were trying to autogenerate them. Instead we now provide
a simple default with the option to override it in an initializer.
This should still work for most shops out of the box while making it
much more flexible for more sophisticated installations.

### CODE REVIEW

**Comment by Tinusw** [comment]
LGTM 👍

**Comment by josetonyp** [comment]
I think I've only found some cosmetic changes. I can do them myself.

**Comment by pascalj** [comment]
Why did you replace all `line_item` with `@line_item`?

**Comment by josetonyp** [comment]
To have same call for the variable all inside the class.

**Comment by pascalj** [comment]
But why [not the other way around](https://en.wikipedia.org/wiki/Uniform_access_principle) then? There is virtually no overhead calling the accessor plus it's easily replaceable by a method if needed.

**Comment by josetonyp** [comment]
Sure why not. It was just cosmetic.

**Pull request merged**
